import {
  Volume2,
  Layers,
  Settings,
  Music,
  Repeat,
  Sliders,
} from 'lucide-react'
import type { AssetSchema } from '../types'

export const audioSchema: AssetSchema = {
  kind: 'audio',
  displayName: 'Sound Event',
  sections: [
    {
      id: 'inheritance',
      title: 'Inheritance',
      icon: Layers,
      collapsible: true,
      defaultExpanded: false,
      properties: [
        {
          key: 'Parent',
          label: 'Parent Asset',
          type: 'string',
          description: 'Parent sound event to inherit from',
          placeholder: 'Optional parent asset',
        },
      ],
      condition: (data) => data.Parent !== undefined,
    },
    {
      id: 'identity',
      title: 'Sound Event Identity',
      icon: Volume2,
      collapsible: true,
      defaultExpanded: true,
      properties: [
        {
          key: 'Name',
          label: 'Event Name',
          type: 'string',
          description: 'Unique identifier for this sound event',
          required: true,
          placeholder: 'e.g., item.sword.swing',
        },
        {
          key: 'Category',
          label: 'Sound Category',
          type: 'select',
          description: 'Audio category for volume control',
          selectConfig: {
            options: [
              { value: 'Master', label: 'Master' },
              { value: 'Music', label: 'Music' },
              { value: 'Ambient', label: 'Ambient' },
              { value: 'Blocks', label: 'Blocks' },
              { value: 'Entities', label: 'Entities' },
              { value: 'Players', label: 'Players' },
              { value: 'Weather', label: 'Weather' },
              { value: 'UI', label: 'UI' },
            ],
          },
        },
        {
          key: 'Subtitle',
          label: 'Subtitle',
          type: 'string',
          description: 'Subtitle text for accessibility',
          placeholder: 'e.g., Sword swings',
        },
      ],
    },
    {
      id: 'playback',
      title: 'Playback Settings',
      icon: Settings,
      collapsible: true,
      defaultExpanded: true,
      properties: [
        {
          key: 'Volume',
          label: 'Volume',
          type: 'number',
          description: 'Base volume (0-1)',
          defaultValue: 1.0,
          numberConfig: { min: 0, max: 1, step: 0.05 },
        },
        {
          key: 'VolumeRandomization',
          label: 'Volume Randomization',
          type: 'number',
          description: 'Random volume variance (+/-)',
          defaultValue: 0,
          numberConfig: { min: 0, max: 0.5, step: 0.05 },
        },
        {
          key: 'Pitch',
          label: 'Pitch',
          type: 'number',
          description: 'Base pitch (1.0 = normal)',
          defaultValue: 1.0,
          numberConfig: { min: 0.5, max: 2.0, step: 0.05 },
        },
        {
          key: 'PitchRandomization',
          label: 'Pitch Randomization',
          type: 'number',
          description: 'Random pitch variance (+/-)',
          defaultValue: 0,
          numberConfig: { min: 0, max: 0.5, step: 0.05 },
        },
        {
          key: 'Attenuation',
          label: 'Attenuation Distance',
          type: 'number',
          description: 'Distance at which sound fades',
          defaultValue: 16,
          numberConfig: { min: 1, max: 64, step: 1 },
        },
      ],
    },
    {
      id: 'looping',
      title: 'Looping',
      icon: Repeat,
      collapsible: true,
      defaultExpanded: false,
      condition: (data) =>
        data.Loop !== undefined ||
        data.LoopDelay !== undefined ||
        data.FadeIn !== undefined,
      properties: [
        {
          key: 'Loop',
          label: 'Loop',
          type: 'boolean',
          description: 'Whether the sound loops',
          defaultValue: false,
        },
        {
          key: 'LoopDelay',
          label: 'Loop Delay',
          type: 'number',
          description: 'Delay between loops in seconds',
          defaultValue: 0,
          numberConfig: { min: 0, step: 0.1, unit: 's' },
        },
        {
          key: 'FadeIn',
          label: 'Fade In',
          type: 'number',
          description: 'Fade in duration in seconds',
          defaultValue: 0,
          numberConfig: { min: 0, step: 0.1, unit: 's' },
        },
        {
          key: 'FadeOut',
          label: 'Fade Out',
          type: 'number',
          description: 'Fade out duration in seconds',
          defaultValue: 0,
          numberConfig: { min: 0, step: 0.1, unit: 's' },
        },
      ],
    },
    {
      id: 'sounds',
      title: 'Sound Layers',
      icon: Music,
      collapsible: true,
      defaultExpanded: true,
      properties: [
        {
          key: 'Sounds',
          label: 'Sound Files',
          type: 'array',
          description: 'Sound files that can play for this event',
          arrayConfig: {
            itemSchema: {
              key: 'soundLayer',
              label: 'Sound Layer',
              type: 'object',
              objectSchema: [
                {
                  key: 'Path',
                  label: 'Sound Path',
                  type: 'path',
                  description: 'Path to the sound file',
                  placeholder: 'Sounds/Items/sword_swing.ogg',
                  pathConfig: {
                    previewType: 'sound',
                    filters: [{ name: 'Audio', extensions: ['ogg', 'wav', 'mp3'] }],
                    suggestedFolder: 'Common/Sounds',
                    pathPrefix: 'Common',
                  },
                },
                {
                  key: 'Weight',
                  label: 'Weight',
                  type: 'number',
                  description: 'Selection weight for random playback',
                  defaultValue: 1,
                  numberConfig: { min: 0, step: 0.1 },
                },
                {
                  key: 'Volume',
                  label: 'Volume Override',
                  type: 'number',
                  description: 'Volume multiplier for this layer',
                  defaultValue: 1.0,
                  numberConfig: { min: 0, max: 2, step: 0.05 },
                },
                {
                  key: 'Pitch',
                  label: 'Pitch Override',
                  type: 'number',
                  description: 'Pitch multiplier for this layer',
                  defaultValue: 1.0,
                  numberConfig: { min: 0.5, max: 2, step: 0.05 },
                },
                {
                  key: 'Stream',
                  label: 'Stream',
                  type: 'boolean',
                  description: 'Stream from disk (for long audio)',
                  defaultValue: false,
                },
              ],
            },
          },
        },
      ],
    },
    {
      id: 'advanced',
      title: 'Advanced',
      icon: Sliders,
      collapsible: true,
      defaultExpanded: false,
      condition: (data) =>
        data.Replace !== undefined ||
        data.Priority !== undefined ||
        data.MaxInstances !== undefined,
      properties: [
        {
          key: 'Replace',
          label: 'Replace',
          type: 'boolean',
          description: 'Replace other sounds of this type',
          defaultValue: false,
        },
        {
          key: 'Priority',
          label: 'Priority',
          type: 'number',
          description: 'Playback priority (higher = more important)',
          defaultValue: 0,
          numberConfig: { min: 0, max: 10, step: 1 },
        },
        {
          key: 'MaxInstances',
          label: 'Max Instances',
          type: 'number',
          description: 'Maximum simultaneous playback instances',
          defaultValue: 0,
          numberConfig: { min: 0, step: 1 },
        },
        {
          key: 'Cooldown',
          label: 'Cooldown',
          type: 'number',
          description: 'Minimum time between plays in seconds',
          defaultValue: 0,
          numberConfig: { min: 0, step: 0.1, unit: 's' },
        },
      ],
    },
  ],
}
