import {
  Layers,
  Sparkles,
  Shield,
  Zap,
  Apple,
  FlaskConical,
  Rocket,
  Hammer,
  Tag,
  Image,
  MousePointer,
  Swords,
  Volume2,
  Wind,
  Box,
  BookOpen,
  Lightbulb,
} from 'lucide-react'
import type { AssetSchema } from '../types'

export const itemSchema: AssetSchema = {
  kind: 'item',
  displayName: 'Item',
  sections: [
    {
      id: 'inheritance',
      title: 'Inheritance',
      icon: Layers,
      collapsible: true,
      defaultExpanded: false,
      properties: [
        {
          key: 'Parent',
          label: 'Parent Asset',
          type: 'string',
          description: 'Parent asset ID to inherit properties from',
          placeholder: 'Optional parent asset',
        },
      ],
      condition: (data) => data.Parent !== undefined,
    },
    {
      id: 'translation',
      title: 'Translation',
      icon: Sparkles,
      collapsible: true,
      defaultExpanded: true,
      properties: [
        {
          key: 'TranslationProperties.Name',
          label: 'Display Name',
          type: 'string',
          placeholder: 'In-game name',
        },
        {
          key: 'TranslationProperties.Description',
          label: 'Description',
          type: 'string',
          placeholder: 'Item description',
        },
        {
          key: 'NameKey',
          label: 'Name Key',
          type: 'string',
          description: 'Localization key for the name',
          placeholder: 'items.my_item.name',
        },
        {
          key: 'DescriptionKey',
          label: 'Description Key',
          type: 'string',
          description: 'Localization key for the description',
          placeholder: 'items.my_item.desc',
        },
      ],
    },
    {
      id: 'identity',
      title: 'Identity & Classification',
      icon: Tag,
      collapsible: true,
      defaultExpanded: true,
      properties: [
        {
          key: 'Quality',
          label: 'Quality',
          type: 'select',
          description: 'Item quality/rarity tier',
          selectConfig: {
            options: [
              { value: 'Junk', label: 'Junk' },
              { value: 'Common', label: 'Common' },
              { value: 'Uncommon', label: 'Uncommon' },
              { value: 'Rare', label: 'Rare' },
              { value: 'Epic', label: 'Epic' },
              { value: 'Legendary', label: 'Legendary' },
              { value: 'Relic', label: 'Relic' },
              { value: 'Template', label: 'Template' },
              { value: 'Developer', label: 'Developer' },
              { value: 'Tool', label: 'Tool' },
              { value: 'Technical', label: 'Technical' },
              { value: 'Debug', label: 'Debug' },
            ],
          },
        },
        {
          key: 'ItemLevel',
          label: 'Item Level',
          type: 'number',
          description: 'Level requirement or power level',
          numberConfig: { min: 1, step: 1 },
        },
        {
          key: 'Categories',
          label: 'Categories',
          type: 'array',
          description: 'Item categories for sorting and filtering',
          arrayConfig: {
            itemSchema: {
              key: 'category',
              label: 'Category',
              type: 'string',
              placeholder: 'e.g., Weapon, Tool, Consumable',
            },
          },
        },
        {
          key: 'Tags.Type',
          label: 'Type Tags',
          type: 'array',
          description: 'Type classification tags',
          arrayConfig: {
            itemSchema: {
              key: 'typeTag',
              label: 'Type',
              type: 'string',
              placeholder: 'e.g., Sword, Food, Potion',
            },
          },
        },
        {
          key: 'Tags.Family',
          label: 'Family Tags',
          type: 'array',
          description: 'Item family grouping tags',
          arrayConfig: {
            itemSchema: {
              key: 'familyTag',
              label: 'Family',
              type: 'string',
              placeholder: 'e.g., Metal, Organic',
            },
          },
        },
      ],
    },
    {
      id: 'visuals',
      title: 'Visuals',
      icon: Layers,
      collapsible: true,
      defaultExpanded: true,
      properties: [
        {
          key: 'Icon',
          label: 'Icon',
          type: 'path',
          placeholder: 'Icons/ItemsGenerated/...',
          pathConfig: {
            previewType: 'image',
            filters: [{ name: 'Images', extensions: ['png', 'jpg', 'jpeg', 'tga', 'dds'] }],
            suggestedFolder: 'Common/Icons/ItemsGenerated',
            pathPrefix: 'Common',
          },
        },
        {
          key: 'Model',
          label: 'Model',
          type: 'path',
          placeholder: 'Items/MyItem.blockymodel',
          pathConfig: {
            previewType: 'none',
            filters: [{ name: 'Blocky Models', extensions: ['blockymodel'] }],
            suggestedFolder: 'Common/Items',
            pathPrefix: 'Common',
          },
        },
        {
          key: 'Texture',
          label: 'Texture',
          type: 'path',
          description: 'Custom texture for the item model',
          placeholder: 'Textures/Items/...',
          pathConfig: {
            previewType: 'image',
            filters: [{ name: 'Images', extensions: ['png', 'jpg', 'jpeg', 'tga', 'dds'] }],
            suggestedFolder: 'Common/Textures/Items',
            pathPrefix: 'Common',
          },
        },
        {
          key: 'DroppedItemAnimation',
          label: 'Dropped Item Animation',
          type: 'path',
          description: 'Animation used when item is dropped in the world',
          placeholder: 'Animations/Items/...',
          pathConfig: {
            previewType: 'none',
            filters: [{ name: 'Blocky Animations', extensions: ['blockyanim'] }],
            suggestedFolder: 'Common/Animations/Items',
            pathPrefix: 'Common',
          },
        },
        {
          key: 'Scale',
          label: 'Scale',
          type: 'number',
          description: 'Visual scale multiplier',
          defaultValue: 1.0,
          numberConfig: { min: 0.1, max: 10, step: 0.1 },
        },
      ],
    },
    {
      id: 'iconProperties',
      title: 'Icon Display',
      icon: Image,
      collapsible: true,
      defaultExpanded: false,
      properties: [
        {
          key: 'IconProperties.Scale',
          label: 'Icon Scale',
          type: 'number',
          description: 'Scale of the item in the inventory icon',
          defaultValue: 1.0,
          numberConfig: { min: 0.1, max: 5, step: 0.1 },
        },
        {
          key: 'IconProperties.Translation',
          label: 'Icon Translation',
          type: 'array',
          description: 'X, Y offset for icon positioning',
          arrayConfig: {
            itemSchema: {
              key: 'offset',
              label: 'Offset',
              type: 'number',
              numberConfig: { step: 0.1 },
            },
            minItems: 2,
            maxItems: 2,
          },
        },
        {
          key: 'IconProperties.Rotation',
          label: 'Icon Rotation',
          type: 'array',
          description: 'X, Y, Z rotation angles for icon display',
          arrayConfig: {
            itemSchema: {
              key: 'angle',
              label: 'Angle',
              type: 'number',
              numberConfig: { min: -360, max: 360, step: 1 },
            },
            minItems: 3,
            maxItems: 3,
          },
        },
      ],
    },
    {
      id: 'properties',
      title: 'Properties',
      icon: Zap,
      collapsible: true,
      defaultExpanded: true,
      properties: [
        {
          key: 'MaxStack',
          label: 'Max Stack',
          type: 'number',
          defaultValue: 64,
          numberConfig: { min: 1, max: 999, step: 1 },
        },
        {
          key: 'Consumable',
          label: 'Consumable',
          type: 'boolean',
          description: 'Whether this item can be consumed',
          defaultValue: false,
        },
      ],
    },
    {
      id: 'durability',
      title: 'Durability',
      icon: Shield,
      collapsible: true,
      defaultExpanded: true,
      condition: (data) =>
        data.MaxDurability !== undefined ||
        data.Durability !== undefined ||
        data.DurabilityLossOnHit !== undefined,
      properties: [
        {
          key: 'MaxDurability',
          label: 'Max Durability',
          type: 'number',
          description: 'Maximum durability points',
          numberConfig: { min: 0, step: 1 },
        },
        {
          key: 'DurabilityLossOnHit',
          label: 'Durability Loss On Hit',
          type: 'number',
          description: 'Durability lost per hit',
          defaultValue: 1,
          numberConfig: { min: 0, step: 1 },
        },
        {
          key: 'Durability',
          label: 'Durability (Legacy)',
          type: 'number',
          description: '0 for no durability',
          defaultValue: 0,
          numberConfig: { min: 0, step: 1 },
        },
      ],
    },
    {
      id: 'animations',
      title: 'Animations',
      icon: Zap,
      collapsible: true,
      defaultExpanded: false,
      properties: [
        {
          key: 'PlayerAnimationsId',
          label: 'Player Animations ID',
          type: 'string',
          description: 'Animation set used when player holds this item',
          placeholder: 'e.g., Sword, Tool, TwoHanded',
        },
        {
          key: 'Reticle',
          label: 'Reticle',
          type: 'string',
          description: 'Crosshair style when holding this item',
          placeholder: 'e.g., Default, Combat, Ranged',
        },
      ],
    },
    {
      id: 'sound',
      title: 'Sound',
      icon: Volume2,
      collapsible: true,
      defaultExpanded: false,
      properties: [
        {
          key: 'ItemSoundSetId',
          label: 'Sound Set ID',
          type: 'string',
          description: 'Sound set used for item interactions',
          placeholder: 'e.g., Metal, Wood, Fabric',
        },
      ],
    },
    {
      id: 'interactions',
      title: 'Interactions',
      icon: MousePointer,
      collapsible: true,
      defaultExpanded: true,
      condition: (data) => data.Interactions !== undefined,
      properties: [
        {
          key: 'Interactions.Primary',
          label: 'Primary Action',
          type: 'string',
          description: 'Action performed on primary use (left click)',
          placeholder: 'e.g., Attack, Use, Place',
        },
        {
          key: 'Interactions.Secondary',
          label: 'Secondary Action',
          type: 'string',
          description: 'Action performed on secondary use (right click)',
          placeholder: 'e.g., Block, AltFire, Eat',
        },
        {
          key: 'Interactions.Ability1',
          label: 'Ability 1',
          type: 'string',
          description: 'Special ability action',
          placeholder: 'e.g., ChargedAttack, ThrowAbility',
        },
      ],
    },
    {
      id: 'utility',
      title: 'Utility',
      icon: Zap,
      collapsible: true,
      defaultExpanded: false,
      condition: (data) => data.Utility !== undefined,
      properties: [
        {
          key: 'Utility.Compatible',
          label: 'Utility Compatible',
          type: 'boolean',
          description: 'Whether this item can be placed in utility slots',
          defaultValue: false,
        },
        {
          key: 'Utility.Usable',
          label: 'Utility Usable',
          type: 'boolean',
          description: 'Whether item can be used from utility slot',
          defaultValue: false,
        },
      ],
    },
    {
      id: 'combat',
      title: 'Combat',
      icon: Shield,
      collapsible: true,
      defaultExpanded: true,
      condition: (data) => data.Attacks !== undefined,
      properties: [
        {
          key: 'Attacks',
          label: 'Attacks',
          type: 'array',
          arrayConfig: {
            itemSchema: {
              key: 'attack',
              label: 'Attack',
              type: 'object',
              objectSchema: [
                { key: 'Damage', label: 'Damage', type: 'number', numberConfig: { min: 0, step: 1 } },
                { key: 'Reach', label: 'Reach', type: 'number', numberConfig: { min: 0, step: 0.1 } },
                {
                  key: 'Time',
                  label: 'Cooldown',
                  type: 'number',
                  numberConfig: { min: 0, step: 0.1, unit: 's' },
                },
              ],
            },
          },
        },
      ],
    },
    {
      id: 'weapon',
      title: 'Weapon Stats',
      icon: Swords,
      collapsible: true,
      defaultExpanded: true,
      condition: (data) => data.Weapon !== undefined,
      properties: [
        {
          key: 'Weapon.StatModifiers',
          label: 'Stat Modifiers',
          type: 'array',
          description: 'Stats modified while wielding this weapon. Format: { "StatName": [{ "Amount": value, "CalculationType": "Additive" }] }',
          arrayConfig: {
            itemSchema: {
              key: 'modifier',
              label: 'Modifier',
              type: 'object',
              objectSchema: [
                {
                  key: 'StatName',
                  label: 'Stat Name',
                  type: 'string',
                  placeholder: 'e.g., SignatureEnergy, AttackSpeed',
                },
                {
                  key: 'Amount',
                  label: 'Amount',
                  type: 'number',
                  numberConfig: { step: 0.1 },
                },
                {
                  key: 'CalculationType',
                  label: 'Calculation Type',
                  type: 'select',
                  selectConfig: {
                    options: [
                      { value: 'Additive', label: 'Additive' },
                      { value: 'Multiplicative', label: 'Multiplicative' },
                      { value: 'Override', label: 'Override' },
                    ],
                  },
                },
              ],
            },
          },
        },
        {
          key: 'Weapon.EntityStatsToClear',
          label: 'Stats To Clear',
          type: 'array',
          description: 'Entity stats cleared when using this weapon',
          arrayConfig: {
            itemSchema: {
              key: 'stat',
              label: 'Stat',
              type: 'string',
              placeholder: 'Stat ID to clear',
            },
          },
        },
      ],
    },
    {
      id: 'itemAppearance',
      title: 'Appearance Effects',
      icon: Sparkles,
      collapsible: true,
      defaultExpanded: false,
      condition: (data) => data.ItemAppearanceConditions !== undefined,
      properties: [
        {
          key: 'ItemAppearanceConditions',
          label: 'Appearance Conditions',
          type: 'array',
          description: 'Conditions that modify item appearance (particles, glow, etc.)',
          arrayConfig: {
            itemSchema: {
              key: 'condition',
              label: 'Condition',
              type: 'object',
              objectSchema: [
                { key: 'Condition', label: 'Condition', type: 'string', placeholder: 'e.g., IsEnchanted' },
                { key: 'Effect', label: 'Effect', type: 'string', placeholder: 'e.g., GlowParticles' },
              ],
            },
          },
        },
      ],
    },
    {
      id: 'resourceTypes',
      title: 'Resource Types',
      icon: Layers,
      collapsible: true,
      defaultExpanded: false,
      condition: (data) => data.ResourceTypes !== undefined,
      properties: [
        {
          key: 'ResourceTypes',
          label: 'Resource Types',
          type: 'array',
          description: 'Resource categories this item belongs to',
          arrayConfig: {
            itemSchema: {
              key: 'resource',
              label: 'Resource',
              type: 'object',
              objectSchema: [
                { key: 'Type', label: 'Type', type: 'string', placeholder: 'e.g., Food, Protein' },
                { key: 'Amount', label: 'Amount', type: 'number', numberConfig: { min: 0, step: 1 } },
              ],
            },
          },
        },
      ],
    },
    {
      id: 'tool',
      title: 'Tool Properties',
      icon: Hammer,
      collapsible: true,
      defaultExpanded: true,
      condition: (data) => data.Tool !== undefined,
      properties: [
        {
          key: 'Tool.Specs',
          label: 'Tool Specs',
          type: 'array',
          description: 'Tool specifications for gathering different block types',
          arrayConfig: {
            itemSchema: {
              key: 'spec',
              label: 'Spec',
              type: 'object',
              objectSchema: [
                {
                  key: 'Power',
                  label: 'Power',
                  type: 'number',
                  description: 'Tool power level',
                  defaultValue: 1,
                  numberConfig: { min: 0, step: 1 },
                },
                {
                  key: 'GatherType',
                  label: 'Gather Type',
                  type: 'select',
                  description: 'Type of blocks this tool can gather',
                  selectConfig: {
                    options: [
                      { value: 'SoftBlocks', label: 'Soft Blocks' },
                      { value: 'Soils', label: 'Soils' },
                      { value: 'Woods', label: 'Woods' },
                      { value: 'Rocks', label: 'Rocks' },
                      { value: 'Benches', label: 'Benches' },
                      { value: 'DungeonBlocks', label: 'Dungeon Blocks' },
                      { value: 'VolcanicRocks', label: 'Volcanic Rocks' },
                    ],
                  },
                },
              ],
            },
          },
        },
        {
          key: 'Tool.DurabilityLossBlockTypes',
          label: 'Durability Loss Block Types',
          type: 'array',
          description: 'Block types that cause durability loss when hit',
          arrayConfig: {
            itemSchema: {
              key: 'blockType',
              label: 'Block Type',
              type: 'object',
              objectSchema: [
                {
                  key: 'BlockSets',
                  label: 'Block Sets',
                  type: 'array',
                  description: 'List of block set identifiers',
                  arrayConfig: {
                    itemSchema: {
                      key: 'blockSet',
                      label: 'Block Set',
                      type: 'string',
                      placeholder: 'e.g., Rocks, Woods',
                    },
                  },
                },
                {
                  key: 'DurabilityLossOnHit',
                  label: 'Durability Loss On Hit',
                  type: 'number',
                  description: 'Durability lost per hit on these blocks',
                  defaultValue: 1,
                  numberConfig: { min: 0, step: 1 },
                },
              ],
            },
          },
        },
      ],
    },
    {
      id: 'armor',
      title: 'Armor Properties',
      icon: Shield,
      collapsible: true,
      defaultExpanded: true,
      condition: (data) => data.Armor !== undefined,
      properties: [
        {
          key: 'Armor.ArmorSlot',
          label: 'Armor Slot',
          type: 'select',
          description: 'Equipment slot for this armor piece',
          selectConfig: {
            options: [
              { value: 'Head', label: 'Head' },
              { value: 'Chest', label: 'Chest' },
              { value: 'Hands', label: 'Hands' },
              { value: 'Legs', label: 'Legs' },
            ],
          },
        },
        {
          key: 'Armor.BaseDamageResistance',
          label: 'Base Damage Resistance',
          type: 'number',
          description: 'Base damage resistance value',
          numberConfig: { min: 0, step: 0.1 },
        },
        {
          key: 'Armor.CosmeticsToHide',
          label: 'Cosmetics To Hide',
          type: 'array',
          description: 'Cosmetic items that should be hidden when wearing this armor',
          arrayConfig: {
            itemSchema: {
              key: 'cosmetic',
              label: 'Cosmetic',
              type: 'string',
              placeholder: 'Cosmetic ID to hide',
            },
          },
        },
        {
          key: 'Armor.StatModifiers',
          label: 'Stat Modifiers',
          type: 'array',
          description: 'Stats modified while wearing this armor (format: { StatName: [{ Amount, CalculationType }] })',
          arrayConfig: {
            itemSchema: {
              key: 'statMod',
              label: 'Stat Modifier',
              type: 'object',
              objectSchema: [
                {
                  key: 'StatName',
                  label: 'Stat Name',
                  type: 'string',
                  placeholder: 'e.g., SignatureEnergy, MaxHealth',
                },
                {
                  key: 'Amount',
                  label: 'Amount',
                  type: 'number',
                  numberConfig: { step: 0.1 },
                },
                {
                  key: 'CalculationType',
                  label: 'Calculation Type',
                  type: 'select',
                  selectConfig: {
                    options: [
                      { value: 'Additive', label: 'Additive' },
                      { value: 'Multiplicative', label: 'Multiplicative' },
                      { value: 'Override', label: 'Override' },
                    ],
                  },
                },
              ],
            },
          },
        },
        {
          key: 'Armor.DamageResistance',
          label: 'Damage Resistance',
          type: 'array',
          description: 'Damage resistance per damage type (Physical, Projectile, etc.)',
          arrayConfig: {
            itemSchema: {
              key: 'resistance',
              label: 'Resistance',
              type: 'object',
              objectSchema: [
                {
                  key: 'DamageType',
                  label: 'Damage Type',
                  type: 'select',
                  selectConfig: {
                    options: [
                      { value: 'Physical', label: 'Physical' },
                      { value: 'Projectile', label: 'Projectile' },
                      { value: 'Fire', label: 'Fire' },
                      { value: 'Ice', label: 'Ice' },
                      { value: 'Lightning', label: 'Lightning' },
                      { value: 'Poison', label: 'Poison' },
                    ],
                  },
                },
                {
                  key: 'Amount',
                  label: 'Amount',
                  type: 'number',
                  numberConfig: { min: 0, step: 0.1 },
                },
                {
                  key: 'CalculationType',
                  label: 'Calculation Type',
                  type: 'select',
                  selectConfig: {
                    options: [
                      { value: 'Additive', label: 'Additive' },
                      { value: 'Multiplicative', label: 'Multiplicative' },
                    ],
                  },
                },
              ],
            },
          },
        },
      ],
    },
    {
      id: 'food',
      title: 'Food Properties',
      icon: Apple,
      collapsible: true,
      defaultExpanded: true,
      condition: (data) => data.FoodProperties !== undefined,
      properties: [
        {
          key: 'FoodProperties.Nutrition',
          label: 'Nutrition',
          type: 'number',
          defaultValue: 4,
          numberConfig: { min: 0, step: 1 },
        },
        {
          key: 'FoodProperties.Saturation',
          label: 'Saturation',
          type: 'number',
          defaultValue: 2.4,
          numberConfig: { min: 0, step: 0.1 },
        },
        {
          key: 'FoodProperties.ConsumeTime',
          label: 'Consume Time',
          type: 'number',
          defaultValue: 1.6,
          numberConfig: { min: 0, step: 0.1, unit: 's' },
        },
        {
          key: 'FoodProperties.CanAlwaysEat',
          label: 'Can Always Eat',
          type: 'boolean',
          defaultValue: false,
        },
      ],
    },
    {
      id: 'potion',
      title: 'Potion Properties',
      icon: FlaskConical,
      collapsible: true,
      defaultExpanded: true,
      condition: (data) => data.PotionProperties !== undefined,
      properties: [
        {
          key: 'PotionProperties.Duration',
          label: 'Duration',
          type: 'number',
          defaultValue: 60,
          numberConfig: { min: 0, step: 1, unit: 's' },
        },
        {
          key: 'PotionProperties.ConsumeTime',
          label: 'Consume Time',
          type: 'number',
          defaultValue: 1.2,
          numberConfig: { min: 0, step: 0.1, unit: 's' },
        },
        {
          key: 'PotionProperties.Effects',
          label: 'Effects',
          type: 'array',
          arrayConfig: {
            itemSchema: {
              key: 'effect',
              label: 'Effect',
              type: 'object',
              objectSchema: [
                { key: 'EffectId', label: 'Effect ID', type: 'string' },
                {
                  key: 'Duration',
                  label: 'Duration',
                  type: 'number',
                  numberConfig: { min: 0, step: 1, unit: 's' },
                },
                { key: 'Amplifier', label: 'Amplifier', type: 'number', numberConfig: { min: 1, step: 1 } },
              ],
            },
          },
        },
      ],
    },
    {
      id: 'projectile',
      title: 'Projectile Properties',
      icon: Rocket,
      collapsible: true,
      defaultExpanded: true,
      condition: (data) => data.ProjectileProperties !== undefined,
      properties: [
        {
          key: 'ProjectileProperties.Damage',
          label: 'Damage',
          type: 'number',
          defaultValue: 5,
          numberConfig: { min: 0, step: 1 },
        },
        {
          key: 'ProjectileProperties.Velocity',
          label: 'Velocity',
          type: 'number',
          defaultValue: 30.0,
          numberConfig: { min: 0, step: 0.5 },
        },
        {
          key: 'ProjectileProperties.Gravity',
          label: 'Gravity',
          type: 'number',
          defaultValue: 0.05,
          numberConfig: { min: 0, step: 0.01 },
        },
      ],
    },
    {
      id: 'cosmetic',
      title: 'Cosmetic Properties',
      icon: Sparkles,
      collapsible: true,
      defaultExpanded: true,
      condition: (data) => data.CosmeticProperties !== undefined,
      properties: [
        {
          key: 'CosmeticProperties.Slot',
          label: 'Slot',
          type: 'select',
          selectConfig: {
            options: [
              { value: 'Back', label: 'Back' },
              { value: 'Head', label: 'Head' },
              { value: 'Face', label: 'Face' },
              { value: 'Shoulder', label: 'Shoulder' },
            ],
          },
        },
        {
          key: 'CosmeticProperties.ClientOnly',
          label: 'Client Only',
          type: 'boolean',
          defaultValue: true,
        },
      ],
    },
    {
      id: 'glider',
      title: 'Glider Properties',
      icon: Wind,
      collapsible: true,
      defaultExpanded: true,
      condition: (data) => data.Glider !== undefined,
      properties: [
        {
          key: 'Glider.GlideSpeed',
          label: 'Glide Speed',
          type: 'number',
          description: 'Horizontal glide speed',
          defaultValue: 1.0,
          numberConfig: { min: 0, step: 0.1 },
        },
        {
          key: 'Glider.FallSpeed',
          label: 'Fall Speed',
          type: 'number',
          description: 'Vertical descent rate',
          defaultValue: 0.5,
          numberConfig: { min: 0, step: 0.1 },
        },
        {
          key: 'Glider.TurnSpeed',
          label: 'Turn Speed',
          type: 'number',
          description: 'Rotation speed while gliding',
          defaultValue: 1.0,
          numberConfig: { min: 0, step: 0.1 },
        },
        {
          key: 'Glider.BoostSpeed',
          label: 'Boost Speed',
          type: 'number',
          description: 'Speed multiplier when boosting',
          numberConfig: { min: 0, step: 0.1 },
        },
        {
          key: 'Glider.Model',
          label: 'Glider Model',
          type: 'path',
          placeholder: 'Items/Gliders/...',
          pathConfig: {
            previewType: 'none',
            filters: [{ name: 'Blocky Models', extensions: ['blockymodel'] }],
            suggestedFolder: 'Common/Items/Gliders',
            pathPrefix: 'Common',
          },
        },
      ],
    },
    {
      id: 'placeableBlock',
      title: 'Placeable Block',
      icon: Box,
      collapsible: true,
      defaultExpanded: false,
      condition: (data) => data.BlockType !== undefined && typeof data.BlockType === 'object',
      properties: [
        {
          key: 'BlockType.Material',
          label: 'Material',
          type: 'string',
          description: 'Block material type',
          placeholder: 'e.g., Stone, Wood, Plant',
        },
        {
          key: 'BlockType.DrawType',
          label: 'Draw Type',
          type: 'select',
          description: 'How the block is rendered',
          selectConfig: {
            options: [
              { value: 'Cube', label: 'Cube' },
              { value: 'CustomModel', label: 'Custom Model' },
              { value: 'Cross', label: 'Cross' },
              { value: 'Flat', label: 'Flat' },
            ],
          },
        },
        {
          key: 'BlockType.HitboxType',
          label: 'Hitbox Type',
          type: 'select',
          description: 'Collision shape',
          selectConfig: {
            options: [
              { value: 'Full', label: 'Full Block' },
              { value: 'None', label: 'None' },
              { value: 'Custom', label: 'Custom' },
            ],
          },
        },
        {
          key: 'BlockType.CustomModel',
          label: 'Custom Model',
          type: 'path',
          placeholder: 'Blocks/Models/...',
          pathConfig: {
            previewType: 'none',
            filters: [{ name: 'Blocky Models', extensions: ['blockymodel'] }],
            suggestedFolder: 'Common/Blocks/Models',
            pathPrefix: 'Common',
          },
        },
        {
          key: 'BlockType.CustomModelScale',
          label: 'Model Scale',
          type: 'number',
          defaultValue: 1.0,
          numberConfig: { min: 0.1, step: 0.1 },
        },
        {
          key: 'BlockType.ParticleColor',
          label: 'Particle Color',
          type: 'string',
          description: 'Hex color for break particles',
          placeholder: '#FFFFFF',
        },
        {
          key: 'BlockType.BlockSoundSetId',
          label: 'Sound Set',
          type: 'string',
          description: 'Sound set for block interactions',
          placeholder: 'e.g., Stone, Wood, Plant',
        },
        {
          key: 'BlockType.BlockParticleSetId',
          label: 'Particle Set',
          type: 'string',
          description: 'Particle set for block effects',
        },
      ],
    },
    {
      id: 'itemEntity',
      title: 'Item Entity',
      icon: Layers,
      collapsible: true,
      defaultExpanded: false,
      condition: (data) => data.ItemEntity !== undefined,
      properties: [
        {
          key: 'ItemEntity.EntityId',
          label: 'Entity ID',
          type: 'string',
          description: 'Entity to spawn when item is used',
          placeholder: 'Entity ID',
        },
        {
          key: 'ItemEntity.SpawnOnUse',
          label: 'Spawn On Use',
          type: 'boolean',
          description: 'Whether to spawn entity when item is used',
          defaultValue: false,
        },
        {
          key: 'ItemEntity.ShowItemParticles',
          label: 'Show Item Particles',
          type: 'boolean',
          description: 'Whether to show particles on the item entity',
          defaultValue: true,
        },
        {
          key: 'ItemEntity.ParticleColor',
          label: 'Particle Color',
          type: 'string',
          description: 'Color of item particles (hex)',
          placeholder: '#FFFFFF',
        },
        {
          key: 'ItemEntity.ParticleSystemId',
          label: 'Particle System ID',
          type: 'string',
          description: 'Custom particle system to use',
          placeholder: 'Particle system identifier',
        },
      ],
    },
    {
      id: 'recipe',
      title: 'Recipe',
      icon: BookOpen,
      collapsible: true,
      defaultExpanded: false,
      condition: (data) => data.Recipe !== undefined,
      properties: [
        {
          key: 'Recipe.TimeSeconds',
          label: 'Craft Time',
          type: 'number',
          description: 'Time in seconds to craft this item',
          defaultValue: 1,
          numberConfig: { min: 0, step: 0.1, unit: 's' },
        },
        {
          key: 'Recipe.KnowledgeRequired',
          label: 'Knowledge Required',
          type: 'boolean',
          description: 'Whether knowledge/recipe must be unlocked first',
          defaultValue: false,
        },
        {
          key: 'Recipe.Input',
          label: 'Input Materials',
          type: 'array',
          description: 'Materials required to craft this item',
          arrayConfig: {
            itemSchema: {
              key: 'input',
              label: 'Input',
              type: 'object',
              objectSchema: [
                {
                  key: 'ItemId',
                  label: 'Item ID',
                  type: 'string',
                  description: 'Specific item ID (or use ResourceTypeId)',
                  placeholder: 'e.g., hytale:iron_ingot',
                },
                {
                  key: 'ResourceTypeId',
                  label: 'Resource Type ID',
                  type: 'string',
                  description: 'Resource type (alternative to ItemId)',
                  placeholder: 'e.g., Metal, Wood',
                },
                {
                  key: 'Quantity',
                  label: 'Quantity',
                  type: 'number',
                  defaultValue: 1,
                  numberConfig: { min: 1, step: 1 },
                },
              ],
            },
          },
        },
        {
          key: 'Recipe.BenchRequirement',
          label: 'Bench Requirements',
          type: 'array',
          description: 'Crafting bench requirements',
          arrayConfig: {
            itemSchema: {
              key: 'bench',
              label: 'Bench',
              type: 'object',
              objectSchema: [
                {
                  key: 'Id',
                  label: 'Bench ID',
                  type: 'string',
                  placeholder: 'e.g., hytale:forge',
                },
                {
                  key: 'Type',
                  label: 'Bench Type',
                  type: 'string',
                  placeholder: 'e.g., Forge, Workbench',
                },
                {
                  key: 'Categories',
                  label: 'Categories',
                  type: 'array',
                  arrayConfig: {
                    itemSchema: {
                      key: 'category',
                      label: 'Category',
                      type: 'string',
                      placeholder: 'Bench category',
                    },
                  },
                },
                {
                  key: 'RequiredTierLevel',
                  label: 'Required Tier Level',
                  type: 'number',
                  description: 'Minimum bench tier required',
                  numberConfig: { min: 0, step: 1 },
                },
              ],
            },
          },
        },
      ],
    },
    {
      id: 'container',
      title: 'Container',
      icon: Box,
      collapsible: true,
      defaultExpanded: false,
      condition: (data) => data.Container !== undefined,
      properties: [
        {
          key: 'Container.Capacity',
          label: 'Capacity',
          type: 'number',
          description: 'Number of slots in this container',
          defaultValue: 9,
          numberConfig: { min: 1, step: 1 },
        },
        {
          key: 'Container.ItemTag',
          label: 'Item Tag Filter',
          type: 'string',
          description: 'Only items with this tag can be stored',
          placeholder: 'e.g., Food, Potion',
        },
      ],
    },
    {
      id: 'particles',
      title: 'Particles',
      icon: Sparkles,
      collapsible: true,
      defaultExpanded: false,
      condition: (data) => data.Particles !== undefined,
      properties: [
        {
          key: 'Particles',
          label: 'Particle Effects',
          type: 'array',
          description: 'Particle systems attached to this item',
          arrayConfig: {
            itemSchema: {
              key: 'particle',
              label: 'Particle',
              type: 'object',
              objectSchema: [
                {
                  key: 'SystemId',
                  label: 'System ID',
                  type: 'string',
                  placeholder: 'Particle system ID',
                },
                {
                  key: 'TargetEntityPart',
                  label: 'Target Entity Part',
                  type: 'string',
                  placeholder: 'e.g., RightHand, Head',
                },
                {
                  key: 'Color',
                  label: 'Color',
                  type: 'string',
                  placeholder: '#FFFFFF',
                },
                {
                  key: 'Scale',
                  label: 'Scale',
                  type: 'number',
                  defaultValue: 1.0,
                  numberConfig: { min: 0.1, step: 0.1 },
                },
                {
                  key: 'RotationOffset',
                  label: 'Rotation Offset',
                  type: 'array',
                  description: 'X, Y, Z rotation offset',
                  arrayConfig: {
                    itemSchema: {
                      key: 'rotation',
                      label: 'Rotation',
                      type: 'number',
                      numberConfig: { min: -360, max: 360, step: 1 },
                    },
                    minItems: 3,
                    maxItems: 3,
                  },
                },
              ],
            },
          },
        },
      ],
    },
    {
      id: 'trails',
      title: 'Trails',
      icon: Wind,
      collapsible: true,
      defaultExpanded: false,
      condition: (data) => data.Trails !== undefined,
      properties: [
        {
          key: 'Trails',
          label: 'Trail Effects',
          type: 'array',
          description: 'Trail effects attached to this item',
          arrayConfig: {
            itemSchema: {
              key: 'trail',
              label: 'Trail',
              type: 'object',
              objectSchema: [
                {
                  key: 'TrailId',
                  label: 'Trail ID',
                  type: 'string',
                  placeholder: 'Trail effect ID',
                },
                {
                  key: 'TargetEntityPart',
                  label: 'Target Entity Part',
                  type: 'string',
                  placeholder: 'e.g., WeaponTip',
                },
                {
                  key: 'TargetNodeName',
                  label: 'Target Node Name',
                  type: 'string',
                  placeholder: 'Model node name',
                },
                {
                  key: 'PositionOffset',
                  label: 'Position Offset',
                  type: 'array',
                  description: 'X, Y, Z position offset',
                  arrayConfig: {
                    itemSchema: {
                      key: 'offset',
                      label: 'Offset',
                      type: 'number',
                      numberConfig: { step: 0.1 },
                    },
                    minItems: 3,
                    maxItems: 3,
                  },
                },
              ],
            },
          },
        },
      ],
    },
    {
      id: 'light',
      title: 'Light',
      icon: Lightbulb,
      collapsible: true,
      defaultExpanded: false,
      condition: (data) => data.Light !== undefined,
      properties: [
        {
          key: 'Light.Color',
          label: 'Light Color',
          type: 'string',
          description: 'Color of emitted light (hex)',
          placeholder: '#FFCC00',
        },
        {
          key: 'Light.Radius',
          label: 'Light Radius',
          type: 'number',
          description: 'How far the light reaches',
          defaultValue: 5,
          numberConfig: { min: 0.1, max: 32, step: 0.5 },
        },
      ],
    },
  ],
}
